github: [allyelvis] # Replace 'allyelvis' with the GitHub username you want to sponsor

patreon: allyelvis # Replace 'allyelvis' with the Patreon username

# Add PayPal account URL as a custom funding platform
custom: ['https://www.paypal.com/paypalme/allyelvis@gmail.com']
